site_name: Theophysics Research Vault
site_description: Complete working vault for internal studies
site_author: David Lowe
site_url: https://theophysics-template.pages.dev
theme:
  name: material
  palette:
  - scheme: slate
    primary: black
    accent: teal
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - search.highlight
  - search.share
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- toc
- tables
plugins:
- search
nav:
- Home: index.md
